"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-07-17 10:24:11.416988
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('main_count', sa.Integer(), nullable=False),
    sa.Column('main_min', sa.Integer(), nullable=False),
    sa.Column('main_max', sa.Integer(), nullable=False),
    sa.Column('bonus_count', sa.Integer(), nullable=False),
    sa.Column('bonus_min', sa.Integer(), nullable=True),
    sa.Column('bonus_max', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('draws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('draw_number', sa.Integer(), nullable=False),
    sa.Column('draw_year', sa.Integer(), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('jackpot_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('prize_pool_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('winners_total', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('validation_status', sa.Enum('pending', 'valid', 'warning', 'invalid', name='validationstatus'), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'draw_year', 'draw_number', name='uq_draw_game_year_number')
    )
    with op.batch_alter_table('draws', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draws_draw_date'), ['draw_date'], unique=False)
        batch_op.create_index('ix_draws_game_date', ['game_id', 'draw_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_draws_game_id'), ['game_id'], unique=False)

    op.create_table('scrape_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('segment', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'segment', name='uq_checkpoint_game_segment')
    )
    with op.batch_alter_table('scrape_checkpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_checkpoints_game_id'), ['game_id'], unique=False)

    op.create_table('validation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('draws_checked', sa.Integer(), nullable=False),
    sa.Column('issues_found', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draw_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('is_bonus', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['draw_id'], ['draws.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draw_id', 'is_bonus', 'position', name='uq_drawnumber_slot')
    )
    with op.batch_alter_table('draw_numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draw_numbers_draw_id'), ['draw_id'], unique=False)
        batch_op.create_index('ix_draw_numbers_value', ['value'], unique=False)

    op.create_table('prize_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('match_count', sa.Integer(), nullable=True),
    sa.Column('winners', sa.Integer(), nullable=True),
    sa.Column('prize_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['draw_id'], ['draws.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draw_id', 'label', name='uq_prizetier_draw_label')
    )
    with op.batch_alter_table('prize_tiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prize_tiers_draw_id'), ['draw_id'], unique=False)

    op.create_table('validation_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('draw_id', sa.Integer(), nullable=True),
    sa.Column('issue_type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draw_id'], ['draws.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['validation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_issues_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_issues_run_id'))

    op.drop_table('validation_issues')
    with op.batch_alter_table('prize_tiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prize_tiers_draw_id'))

    op.drop_table('prize_tiers')
    with op.batch_alter_table('draw_numbers', schema=None) as batch_op:
        batch_op.drop_index('ix_draw_numbers_value')
        batch_op.drop_index(batch_op.f('ix_draw_numbers_draw_id'))

    op.drop_table('draw_numbers')
    op.drop_table('validation_runs')
    with op.batch_alter_table('scrape_checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_checkpoints_game_id'))

    op.drop_table('scrape_checkpoints')
    with op.batch_alter_table('draws', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draws_game_id'))
        batch_op.drop_index('ix_draws_game_date')
        batch_op.drop_index(batch_op.f('ix_draws_draw_date'))

    op.drop_table('draws')
    op.drop_table('games')
    # ### end Alembic commands ###
